"""specialty_update

Revision ID: 2e1bc760e8e7
Revises: 6e6e5a9357ad
Create Date: 2026-03-03 20:44:05.861721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1bc760e8e7'
down_revision = '6e6e5a9357ad'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DELETE FROM user_specialties;")
    op.execute("DELETE FROM specialties;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialties', sa.Column('code', sa.String(length=16), nullable=True))
    op.drop_index(op.f('ix_specialties_profession_id'), table_name='specialties')
    op.create_index(op.f('ix_specialties_code'), 'specialties', ['code'], unique=True)
    op.drop_constraint(op.f('specialties_profession_id_fkey'), 'specialties', type_='foreignkey')
    op.drop_column('specialties', 'profession_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialties', sa.Column('profession_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('specialties_profession_id_fkey'), 'specialties', 'professions', ['profession_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_specialties_code'), table_name='specialties')
    op.create_index(op.f('ix_specialties_profession_id'), 'specialties', ['profession_id'], unique=False)
    op.drop_column('specialties', 'code')
    # ### end Alembic commands ###
