"""Make attachments polymorphic

Revision ID: 2fb9213eb49f
Revises: a9f3c2b1d8e4
Create Date: 2026-03-08 21:48:36.078587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb9213eb49f'
down_revision = 'a9f3c2b1d8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionamos como nullable=True provisoriamente
    op.add_column('attachments', sa.Column('entity_id', sa.Uuid(), nullable=True))
    op.add_column('attachments', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('attachments', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('attachments', sa.Column('file_key', sa.String(length=255), nullable=True))
    
    # Migra os dados existentes (copia user_id para entity_id e seta 'user' no tipo)
    op.execute("UPDATE attachments SET entity_id = user_id, entity_type = 'user' WHERE user_id IS NOT NULL")
    
    # Agora obriga a ser Not Null daqui em diante
    op.alter_column('attachments', 'entity_id', existing_type=sa.Uuid(), nullable=False)
    op.alter_column('attachments', 'entity_type', existing_type=sa.String(length=50), nullable=False)

    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.drop_constraint('documents_user_id_fkey', 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona a coluna de volta como nullable=True
    op.add_column('attachments', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    
    # Copia os dados de volta para a coluna antiga
    op.execute("UPDATE attachments SET user_id = entity_id WHERE entity_type = 'user'")
    
    # Opcional (se havia garantia):
    # op.alter_column('attachments', 'user_id', existing_type=sa.UUID(), nullable=False)

    op.create_foreign_key('documents_user_id_fkey', 'attachments', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_column('attachments', 'file_key')
    op.drop_column('attachments', 'description')
    op.drop_column('attachments', 'entity_type')
    op.drop_column('attachments', 'entity_id')
    # ### end Alembic commands ###
