"""Add institution_id to shift_types

Revision ID: 4137230aa97b
Revises: be698ae17eb7
Create Date: 2026-02-20 18:07:32.441382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4137230aa97b'
down_revision = 'be698ae17eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_types', sa.Column('institution_id', sa.Uuid(), nullable=True))

    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT id FROM institutions LIMIT 1")).fetchone()

    if result:
        default_institution_id = result[0]
        bind.execute(
            sa.text("UPDATE shift_types SET institution_id = :inst_id").bindparams(inst_id=default_institution_id)
        )

    # op.alter_column('shift_types', 'institution_id', nullable=False)

    op.create_index(op.f('ix_shift_types_institution_id'), 'shift_types', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'shift_types', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_types', type_='foreignkey')
    op.drop_index(op.f('ix_shift_types_institution_id'), table_name='shift_types')
    op.drop_column('shift_types', 'institution_id')
    # ### end Alembic commands ###
