"""add_user_status

Revision ID: 6659acb001e9
Revises: b24e8d1a254d
Create Date: 2026-02-26 11:46:09.301565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6659acb001e9'
down_revision = 'b24e8d1a254d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('REGISTERED', 'APPROVED', 'PENDING', 'REJECTED', name='user_status', native_enum=False), server_default='REGISTERED', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
