"""add_issue_date_to_professional_crm

Revision ID: 682d220be62f
Revises: b2c3d4e5f6a7
Create Date: 2026-03-02 22:58:58.017094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682d220be62f'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_crm', sa.Column('issue_date', sa.Date(), nullable=True))

    # Backfill: garante que nenhum shift_type fique com institution_id NULL
    # antes de setar a constraint NOT NULL
    conn = op.get_bind()
    first_institution = conn.execute(
        sa.text("SELECT id FROM institutions ORDER BY created_at LIMIT 1")
    ).fetchone()

    if first_institution:
        conn.execute(
            sa.text(
                "UPDATE shift_types SET institution_id = :institution_id "
                "WHERE institution_id IS NULL"
            ),
            {"institution_id": first_institution[0]},
        )
    else:
        conn.execute(sa.text("DELETE FROM shift_types WHERE institution_id IS NULL"))

    op.alter_column('shift_types', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    # op.drop_index(op.f('ix_users_first_name_trgm'), table_name='users', postgresql_ops={'first_name': 'gin_trgm_ops'}, postgresql_using='gin')
    # op.drop_index(op.f('ix_users_last_name_trgm'), table_name='users', postgresql_ops={'last_name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_users_last_name_trgm'), 'users', ['last_name'], unique=False, postgresql_ops={'last_name': 'gin_trgm_ops'}, postgresql_using='gin')
    # op.create_index(op.f('ix_users_first_name_trgm'), 'users', ['first_name'], unique=False, postgresql_ops={'first_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('shift_types', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('professional_crm', 'issue_date')
    # ### end Alembic commands ###
