"""Add REPROVED to TimesheetStatus

Revision ID: 6d659bbb2629
Revises: ca23e3d374d5
Create Date: 2026-02-16 19:48:13.302585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d659bbb2629'
down_revision = 'ca23e3d374d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping indexes that were never created (commented out in initial migration)
    # op.drop_index(op.f('ix_users_created_at_id'), table_name='users')
    # op.drop_index(op.f('ix_users_first_name_trgm'), table_name='users', postgresql_ops={'first_name': 'gin_trgm_ops'}, postgresql_using='gin')
    # op.drop_index(op.f('ix_users_last_name_trgm'), table_name='users', postgresql_ops={'last_name': 'gin_trgm_ops'}, postgresql_using='gin')
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE timesheetstatus ADD VALUE IF NOT EXISTS 'REPROVED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip recreating indexes that were never created in the initial migration
    # op.create_index(op.f('ix_users_last_name_trgm'), 'users', ['last_name'], unique=False, postgresql_using='gin', postgresql_ops={'last_name': 'gin_trgm_ops'})
    # op.create_index(op.f('ix_users_first_name_trgm'), 'users', ['first_name'], unique=False, postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops'})
    # op.create_index(op.f('ix_users_created_at_id'), 'users', ['created_at', 'id'], unique=False)
    pass  # Cannot undo adding a value to an enum type
    # ### end Alembic commands ###
