"""add_institution_contract_sector_values

Revision ID: b24e8d1a254d
Revises: c8536500c647
Create Date: 2026-02-25 16:58:12.687646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24e8d1a254d'
down_revision = 'c8536500c647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_contract_sector_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_contract_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('hourly_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_contract_id'], ['institution_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_contract_sector_values_id'), 'institution_contract_sector_values', ['id'], unique=False)
    op.create_index(op.f('ix_institution_contract_sector_values_institution_contract_id'), 'institution_contract_sector_values', ['institution_contract_id'], unique=False)
    op.create_index(op.f('ix_institution_contract_sector_values_sector_id'), 'institution_contract_sector_values', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_contract_sector_values_sector_id'), table_name='institution_contract_sector_values')
    op.drop_index(op.f('ix_institution_contract_sector_values_institution_contract_id'), table_name='institution_contract_sector_values')
    op.drop_index(op.f('ix_institution_contract_sector_values_id'), table_name='institution_contract_sector_values')
    op.drop_table('institution_contract_sector_values')
    # ### end Alembic commands ###
