"""add_institution_contract_table

Revision ID: c8536500c647
Revises: 5bb0ff0d00e4
Create Date: 2026-02-25 16:50:30.857464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8536500c647'
down_revision = '5bb0ff0d00e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('FIXED_MONTHLY', 'CONSULTATION_COUNT', 'HOURLY_RATE_PER_SECTOR', name='contract_type', native_enum=False), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_contracts_id'), 'institution_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_institution_contracts_institution_id'), 'institution_contracts', ['institution_id'], unique=False)
    op.create_index(op.f('ix_institution_contracts_user_id'), 'institution_contracts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_contracts_user_id'), table_name='institution_contracts')
    op.drop_index(op.f('ix_institution_contracts_institution_id'), table_name='institution_contracts')
    op.drop_index(op.f('ix_institution_contracts_id'), table_name='institution_contracts')
    op.drop_table('institution_contracts')
    # ### end Alembic commands ###
