"""Initial migration

Revision ID: ca23e3d374d5
Revises:
Create Date: 2026-02-16 18:45:38.055754

"""

from alembic import op
import sqlalchemy as sa

from app.core.cpf import CpfType
from app.core.phone import PhoneType
from app.core.cnpj import CnpjType
import uuid_utils
from datetime import datetime


# revision identifiers, used by Alembic.
revision = "ca23e3d374d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_professions_id"), "professions", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "shift_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shift_types_id"), "shift_types", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("pendency", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cpf", CpfType(length=11), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("phone", PhoneType(length=15), nullable=True),
        sa.Column("profile_picture", sa.String(length=255), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_cpf"), "users", ["cpf"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column("street", sa.String(length=255), nullable=False),
        sa.Column("number", sa.String(length=25), nullable=False),
        sa.Column("complement", sa.String(length=255), nullable=True),
        sa.Column("neighborhood", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_city"), "addresses", ["city"], unique=False)
    op.create_index(op.f("ix_addresses_complement"), "addresses", ["complement"], unique=False)
    op.create_index(op.f("ix_addresses_id"), "addresses", ["id"], unique=False)
    op.create_index(op.f("ix_addresses_neighborhood"), "addresses", ["neighborhood"], unique=False)
    op.create_index(op.f("ix_addresses_number"), "addresses", ["number"], unique=False)
    op.create_index(op.f("ix_addresses_street"), "addresses", ["street"], unique=False)
    op.create_index(op.f("ix_addresses_uf"), "addresses", ["uf"], unique=False)
    op.create_index(op.f("ix_addresses_user_id"), "addresses", ["user_id"], unique=False)
    op.create_index(op.f("ix_addresses_zip_code"), "addresses", ["zip_code"], unique=False)
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("bank_code", sa.String(length=10), nullable=False),
        sa.Column("bank_name", sa.String(length=255), nullable=False),
        sa.Column("agency", sa.String(length=10), nullable=False),
        sa.Column("account_number", sa.String(length=20), nullable=False),
        sa.Column("account_digit", sa.String(length=2), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bank_accounts_id"), "bank_accounts", ["id"], unique=False)
    op.create_index(op.f("ix_bank_accounts_user_id"), "bank_accounts", ["user_id"], unique=False)
    op.create_table(
        "complementary_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "marital_status",
            sa.Enum(
                "SINGLE",
                "MARRIED",
                "DIVORCED",
                "WIDOWED",
                "DOMESTIC_PARTNERSHIP",
                name="maritalstatusenum",
            ),
            nullable=True,
        ),
        sa.Column("place_of_birth", sa.String(length=255), nullable=True),
        sa.Column("nationality", sa.String(length=255), nullable=True),
        sa.Column("mother_name", sa.String(length=255), nullable=True),
        sa.Column("father_name", sa.String(length=255), nullable=True),
        sa.Column("has_disability", sa.Boolean(), nullable=True),
        sa.Column("disability", sa.String(length=500), nullable=True),
        sa.Column(
            "gender",
            sa.Enum(
                "MALE",
                "FEMALE",
                "NON_BINARY",
                "TRANSGENDER",
                "OTHER",
                "PREFER_NOT_TO_SAY",
                name="genderenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "race",
            sa.Enum(
                "WHITE",
                "BLACK",
                "BROWN",
                "ASIAN",
                "INDIGENOUS",
                "PREFER_NOT_TO_SAY",
                name="raceenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_complementary_data_id"), "complementary_data", ["id"], unique=False)
    op.create_index(
        op.f("ix_complementary_data_user_id"), "complementary_data", ["user_id"], unique=True
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("uf", sa.String(length=2), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "RG",
                "CNH",
                "CRM",
                "CNS",
                "SUS",
                "VACCINATION_CARD",
                "PROOF_OF_ADDRESS",
                name="documentsourceenum",
            ),
            nullable=False,
        ),
        sa.Column("file_url", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("issuing_body", sa.String(length=255), nullable=True),
        sa.Column("issuing_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_table(
        "pix_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_pix_keys_id"), "pix_keys", ["id"], unique=False)
    op.create_index(op.f("ix_pix_keys_user_id"), "pix_keys", ["user_id"], unique=False)
    op.create_table(
        "specialties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profession_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profession_id"], ["professions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_specialties_id"), "specialties", ["id"], unique=False)
    op.create_index(
        op.f("ix_specialties_profession_id"), "specialties", ["profession_id"], unique=False
    )
    op.create_table(
        "users_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_roles_id"), "users_roles", ["id"], unique=False)
    op.create_index(op.f("ix_users_roles_role_id"), "users_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_users_roles_user_id"), "users_roles", ["user_id"], unique=False)
    op.create_table(
        "institutions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("social_name", sa.String(length=255), nullable=False),
        sa.Column("tax_document", CnpjType(length=14), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("address_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_institutions_display_name"), "institutions", ["display_name"], unique=False
    )
    op.create_index(op.f("ix_institutions_id"), "institutions", ["id"], unique=False)
    op.create_index(
        op.f("ix_institutions_social_name"), "institutions", ["social_name"], unique=False
    )
    op.create_index(
        op.f("ix_institutions_tax_document"), "institutions", ["tax_document"], unique=False
    )
    op.create_table(
        "user_professions_specialties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("profession_id", sa.Uuid(), nullable=False),
        sa.Column("specialty_id", sa.Uuid(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profession_id"], ["professions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["specialty_id"], ["specialties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "profession_id", "specialty_id", name="uq_user_profession_specialty"
        ),
    )
    op.create_index(
        op.f("ix_user_professions_specialties_id"),
        "user_professions_specialties",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_professions_specialties_profession_id"),
        "user_professions_specialties",
        ["profession_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_professions_specialties_specialty_id"),
        "user_professions_specialties",
        ["specialty_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_professions_specialties_user_id"),
        "user_professions_specialties",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "sectors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sectors_display_name"), "sectors", ["display_name"], unique=False)
    op.create_index(op.f("ix_sectors_id"), "sectors", ["id"], unique=False)
    op.create_table(
        "shifts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("sector_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("shift_type_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=False),
        sa.Column("end_time", sa.String(), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("base_value", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("allow_flexible_hours", sa.Boolean(), nullable=False),
        sa.Column("requires_geolocation", sa.Boolean(), nullable=False),
        sa.Column("shift_weight", sa.Float(), nullable=False),
        sa.Column("doctor_group", sa.String(), nullable=True),
        sa.Column("vacancy_count", sa.Integer(), nullable=True),
        sa.Column("days_of_week", sa.JSON(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("additional_hourly_rate", sa.Float(), nullable=True),
        sa.Column("weekend_hourly_rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sector_id"],
            ["sectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_type_id"],
            ["shift_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shifts_id"), "shifts", ["id"], unique=False)
    op.create_index(op.f("ix_shifts_institution_id"), "shifts", ["institution_id"], unique=False)
    op.create_index(op.f("ix_shifts_sector_id"), "shifts", ["sector_id"], unique=False)
    op.create_table(
        "user_absences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("sector_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "HOLIDAY", "VACATION", "TIME_OFF", "LICENSE", "EXCHANGE", name="absencetypeenum"
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sector_id"],
            ["sectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_absences_id"), "user_absences", ["id"], unique=False)
    op.create_index(op.f("ix_user_absences_user_id"), "user_absences", ["user_id"], unique=False)
    op.create_table(
        "user_timesheets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("sector_id", sa.Uuid(), nullable=False),
        sa.Column("competence_date", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "IN_PROGRESS",
                "PROCESSING",
                "IN_ANALYSIS",
                "RELEASED",
                "CLOSED",
                "PAID",
                "OPEN",
                name="timesheetstatus",
            ),
            nullable=False,
        ),
        sa.Column("total_hours_planned", sa.Float(), nullable=False),
        sa.Column("total_hours_realized", sa.Float(), nullable=False),
        sa.Column("total_value_planned", sa.Float(), nullable=False),
        sa.Column("total_value_payable", sa.Float(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sector_id"],
            ["sectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_timesheets_id"), "user_timesheets", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_timesheets_user_id"), "user_timesheets", ["user_id"], unique=False
    )
    op.create_table(
        "shift_slot_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("fixed_user_id", sa.Uuid(), nullable=True),
        sa.Column("is_fixed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shift_slot_configs_id"), "shift_slot_configs", ["id"], unique=False)
    op.create_table(
        "user_shifts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_timesheet_id", sa.Uuid(), nullable=True),
        sa.Column("shift_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("competence_date", sa.String(), nullable=False),
        sa.Column("planned_start", sa.DateTime(), nullable=False),
        sa.Column("planned_end", sa.DateTime(), nullable=False),
        sa.Column("agreed_value", sa.Float(), nullable=False),
        sa.Column("checkin_time", sa.DateTime(), nullable=True),
        sa.Column("checkout_time", sa.DateTime(), nullable=True),
        sa.Column("checkin_lat", sa.Float(), nullable=True),
        sa.Column("checkin_long", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "PLANNED",
                "CONFIRMED",
                "IN_PROGRESS",
                "COMPLETED",
                "MISSED",
                "SWAPPED",
                "CANCELED",
                name="shiftstatus",
            ),
            nullable=False,
        ),
        sa.Column("needs_assistance", sa.Boolean(), nullable=False),
        sa.Column("assistance_reason", sa.String(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("hours_worked", sa.Float(), nullable=False),
        sa.Column("final_value", sa.Float(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("assistance_user_id", sa.Uuid(), nullable=True),
        sa.Column("slot_config_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assistance_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_config_id"],
            ["shift_slot_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_timesheet_id"],
            ["user_timesheets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_shifts_competence_date"), "user_shifts", ["competence_date"], unique=False
    )
    op.create_index(op.f("ix_user_shifts_id"), "user_shifts", ["id"], unique=False)
    op.create_index(op.f("ix_user_shifts_user_id"), "user_shifts", ["user_id"], unique=False)
    op.create_table(
        "shift_exchanges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_shift_id", sa.Uuid(), nullable=False),
        sa.Column("target_user_id", sa.Uuid(), nullable=True),
        sa.Column("old_person_id", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING_APPROVAL", "APPROVED", "REJECTED", name="shiftexchangestatusenum"),
            nullable=False,
        ),
        sa.Column("manager_notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["old_person_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_shift_id"],
            ["user_shifts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shift_exchanges_id"), "shift_exchanges", ["id"], unique=False)

    roles_table = sa.table(
        "roles",
        sa.column("id", sa.Uuid),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("is_active", sa.Boolean),
    )

    op.bulk_insert(
        roles_table,
        [
            {
                "id": str(uuid_utils.uuid7()),
                "name": "admin",
                "description": "System administrator",
                "is_active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "manager",
                "description": "Institution manager",
                "is_active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "professional",
                "description": "Institution professional",
                "is_active": True,
            },
        ],
    )

    shift_types_table = sa.table(
        "shift_types",
        sa.Column("id", sa.Uuid),
        sa.Column("name", sa.String),
        sa.Column("created_at", sa.DateTime),
        sa.Column("active", sa.Boolean),
    )

    now = datetime.now()

    op.bulk_insert(
        shift_types_table,
        [
            {"id": str(uuid_utils.uuid7()), "name": "NORMAL", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "A DISTANCIA DIURNO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "A DISTANCIA NOTURNO",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "A VISTA", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "ALOJAMENTO - SAB E DOM / FERIADO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "ALOJAMENTO - SEG A SEX",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "AMARELA", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "AME - ANESTOLOGIA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "AME - MAUA NEURO",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "CC DIURNO", "created_at": now, "active": True},
            {"id": str(uuid_utils.uuid7()), "name": "CC MANHÃ", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CC NOTURNO",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "CC TARDE", "created_at": now, "active": True},
            {"id": str(uuid_utils.uuid7()), "name": "CINDERELA", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CINDERELA -PEDIATRIA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CINDERELA - PEDIATRIA FINAL DE SEMANA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CINDERELA FINAL DE SEMANA - ACÁCIAS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CINDERELA SEGUNDA FEIRA - ACÁCIAS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CIRURGIA GERAL - HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CIRURGIA GERAL - MATUTINO FINAL DE SEMANA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CLINICA MÉDICA - CAMBUI",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CLINICA MÉDICA - TRIAGEM - HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "COORDENAÇÃO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "CUIDADOS PALIATIVOS",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "DIARISMO", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "DIARISMO - UTI HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "DIURNO", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "DIURNO FINAL SEMANA - ACÁCIAS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "DIURNO SEMAN -ACÁCIAS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "EMERGÊNCIA -HOSPITAL HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "ENFERMARIA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "ENFERMARIA 1",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "ENFERMARIA 2",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "ENFERMARIA DE CLINICA MEDICA - HOSPITAL HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "FINAL DE SEMANA DIURNO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "FINAL DE SEMANA NOTURNO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "GINECOLOGIA/OBSTETRÍCIA - OURO FINO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "GO - FINAL DE SEMANA CAMBUI",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "GO - SEMANA CAMBUI",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NÃO PRESENCIAL - OURO FINO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NEONATAL - DIARISTA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NEONATAL - SAB E DOM / FERIADO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NEONATAL - SEG A SEX",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NEUROCIRURGIA - FINAL DE SEMANA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NEUROCIRURGIA - HOSPITAL HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "NOTURNO", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NOTURNO FINAL DE SEMANA - ACÁCIAS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "NOTURNO SEMANA - ACÁCIAS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "OBSERVAÇÃO HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "P.S MANHÃ", "created_at": now, "active": True},
            {"id": str(uuid_utils.uuid7()), "name": "P.S TARDE", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PEDIATRIA - ENFERMARIA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PEDIATRIA - OURO FINO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PEDIATRIA - SAB E DOM",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PEDIATRIA - SEG A SEX",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PEDIATRIA FINAL DE SEMANA - CAMBUI",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PEDIATRIA SEMANA - CAMBUI",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PMA COBERTURA - AMERICANA",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PMA FIXO - AMERICANA",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "PORTA", "created_at": now, "active": True},
            {
                "id": str(uuid_utils.uuid7()),
                "name": "PRECEPTORIA - GUARULHOS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "REMOÇÃO / TRANSPORTE PACIENTE",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "SOBREAVISO",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "UTI - DIARISMO - HOSPITAL HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "UTI - HOSPITAL HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {
                "id": str(uuid_utils.uuid7()),
                "name": "UTI 2 HOSPITAL HELIOPOLIS",
                "created_at": now,
                "active": True,
            },
            {"id": str(uuid_utils.uuid7()), "name": "VERMELHA", "created_at": now, "active": True},
            {"id": str(uuid_utils.uuid7()), "name": "VISITA", "created_at": now, "active": True},
        ],
    )

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # Speed up name filter: first_name/last_name ILIKE '%...%'.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_users_first_name_trgm ON users USING gin (first_name gin_trgm_ops);"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_users_last_name_trgm ON users USING gin (last_name gin_trgm_ops);"
    )

    # Make pagination deterministic and efficient for the default ORDER BY.
    # op.execute("CREATE INDEX IF NOT EXISTS ix_users_created_at_id ON users (created_at DESC, id);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shift_exchanges_id"), table_name="shift_exchanges")
    op.drop_table("shift_exchanges")
    op.drop_index(op.f("ix_user_shifts_user_id"), table_name="user_shifts")
    op.drop_index(op.f("ix_user_shifts_id"), table_name="user_shifts")
    op.drop_index(op.f("ix_user_shifts_competence_date"), table_name="user_shifts")
    op.drop_table("user_shifts")
    op.drop_index(op.f("ix_shift_slot_configs_id"), table_name="shift_slot_configs")
    op.drop_table("shift_slot_configs")
    op.drop_index(op.f("ix_user_timesheets_user_id"), table_name="user_timesheets")
    op.drop_index(op.f("ix_user_timesheets_id"), table_name="user_timesheets")
    op.drop_table("user_timesheets")
    op.drop_index(op.f("ix_user_absences_user_id"), table_name="user_absences")
    op.drop_index(op.f("ix_user_absences_id"), table_name="user_absences")
    op.drop_table("user_absences")
    op.drop_index(op.f("ix_shifts_sector_id"), table_name="shifts")
    op.drop_index(op.f("ix_shifts_institution_id"), table_name="shifts")
    op.drop_index(op.f("ix_shifts_id"), table_name="shifts")
    op.drop_table("shifts")
    op.drop_index(op.f("ix_sectors_id"), table_name="sectors")
    op.drop_index(op.f("ix_sectors_display_name"), table_name="sectors")
    op.drop_table("sectors")
    op.drop_index(
        op.f("ix_user_professions_specialties_user_id"), table_name="user_professions_specialties"
    )
    op.drop_index(
        op.f("ix_user_professions_specialties_specialty_id"),
        table_name="user_professions_specialties",
    )
    op.drop_index(
        op.f("ix_user_professions_specialties_profession_id"),
        table_name="user_professions_specialties",
    )
    op.drop_index(
        op.f("ix_user_professions_specialties_id"), table_name="user_professions_specialties"
    )
    op.drop_table("user_professions_specialties")
    op.drop_index(op.f("ix_institutions_tax_document"), table_name="institutions")
    op.drop_index(op.f("ix_institutions_social_name"), table_name="institutions")
    op.drop_index(op.f("ix_institutions_id"), table_name="institutions")
    op.drop_index(op.f("ix_institutions_display_name"), table_name="institutions")
    op.drop_table("institutions")
    op.drop_index(op.f("ix_users_roles_user_id"), table_name="users_roles")
    op.drop_index(op.f("ix_users_roles_role_id"), table_name="users_roles")
    op.drop_index(op.f("ix_users_roles_id"), table_name="users_roles")
    op.drop_table("users_roles")
    op.drop_index(op.f("ix_specialties_profession_id"), table_name="specialties")
    op.drop_index(op.f("ix_specialties_id"), table_name="specialties")
    op.drop_table("specialties")
    op.drop_index(op.f("ix_pix_keys_user_id"), table_name="pix_keys")
    op.drop_index(op.f("ix_pix_keys_id"), table_name="pix_keys")
    op.drop_table("pix_keys")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_complementary_data_user_id"), table_name="complementary_data")
    op.drop_index(op.f("ix_complementary_data_id"), table_name="complementary_data")
    op.drop_table("complementary_data")
    op.drop_index(op.f("ix_bank_accounts_user_id"), table_name="bank_accounts")
    op.drop_index(op.f("ix_bank_accounts_id"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_index(op.f("ix_addresses_zip_code"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_user_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_uf"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_street"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_number"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_neighborhood"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_complement"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_city"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_cpf"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_shift_types_id"), table_name="shift_types")
    op.drop_table("shift_types")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_professions_id"), table_name="professions")
    op.drop_table("professions")
    # ### end Alembic commands ###
