"""Add professional location binding

Revision ID: ebbbbc5b87d9
Revises: 2fb9213eb49f
Create Date: 2026-03-11 15:44:05.783362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbbbc5b87d9'
down_revision = '2fb9213eb49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_location_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('contract_type', sa.Enum('PJ', 'CLT', name='binding_contract_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELED', 'TERMINATED', name='binding_status', native_enum=False), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', name='uq_professional_location')
    )
    op.create_index(op.f('ix_professional_location_bindings_id'), 'professional_location_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_professional_location_bindings_institution_id'), 'professional_location_bindings', ['institution_id'], unique=False)
    op.create_index(op.f('ix_professional_location_bindings_user_id'), 'professional_location_bindings', ['user_id'], unique=False)
    op.create_table('professional_location_sectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('binding_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['binding_id'], ['professional_location_bindings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binding_id', 'sector_id', name='uq_professional_binding_sector')
    )
    op.create_index(op.f('ix_professional_location_sectors_binding_id'), 'professional_location_sectors', ['binding_id'], unique=False)
    op.create_index(op.f('ix_professional_location_sectors_id'), 'professional_location_sectors', ['id'], unique=False)
    op.create_index(op.f('ix_professional_location_sectors_sector_id'), 'professional_location_sectors', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_location_sectors_sector_id'), table_name='professional_location_sectors')
    op.drop_index(op.f('ix_professional_location_sectors_id'), table_name='professional_location_sectors')
    op.drop_index(op.f('ix_professional_location_sectors_binding_id'), table_name='professional_location_sectors')
    op.drop_table('professional_location_sectors')
    op.drop_index(op.f('ix_professional_location_bindings_user_id'), table_name='professional_location_bindings')
    op.drop_index(op.f('ix_professional_location_bindings_institution_id'), table_name='professional_location_bindings')
    op.drop_index(op.f('ix_professional_location_bindings_id'), table_name='professional_location_bindings')
    op.drop_table('professional_location_bindings')
    # ### end Alembic commands ###
